from classic_image_classification.machine_learning.feature_extractor import FeatureExtractor
from classic_image_classification.machine_learning.aggregator import Aggregator
from classic_image_classification.machine_learning.classifier import Classifier
from classic_image_classification.machine_learning.classic_image_classifier import ClassicImageClassifier
from classic_image_classification.machine_learning.optimizing_image_classifier import OptimizingImageClassifier
from classic_image_classification.machine_learning.ensemble_image_classifier import EnsembleImageClassifier
